# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
