# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_auto_20170919_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(related_name='User_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
