# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0010_auto_20170921_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cookbook',
        ),
        migrations.AddField(
            model_name='recipe',
            name='user_cookbook',
            field=models.ManyToManyField(related_name='cookbook', to=settings.AUTH_USER_MODEL),
        ),
    ]
