# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0011_auto_20170921_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user_cookbook',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cookbook_users',
            field=models.ManyToManyField(related_name='cookbooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
