# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 20:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20170921_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cookbook_users',
            field=models.ManyToManyField(related_name='cookbook', to=settings.AUTH_USER_MODEL),
        ),
    ]
