# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20170921_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='procedures',
            field=models.TextField(default='procedures placeholder'),
            preserve_default=False,
        ),
    ]
